---
apiVersion: v1
kind: Secret
metadata:
  name: counter-service
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@github.com:ItayAmitDevOps/counter-service.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----


                 key here


    -----END OPENSSH PRIVATE KEY-----
  insecure: "false"
  enableLfs: "true"
